### PR TITLE
correct data race in wsl/driver

### LINKED ISSUE #228: data race in HEAD
Just got this in my CI. It's a data race inside of rules_webtesting.

Looks `cmd.Wait` is accessed in multiple goroutines in an unsafe way at https://github.com/bazelbuild/rules_webtesting/blob/master/go/wsl/driver/driver.go#L100 and then again at https://github.com/bazelbuild/rules_webtesting/blob/master/go/wsl/hub/hub.go#L231

(cmd.Wait actually does writes to the cmd struct, which is surprising to lots of folks, and a fairly common mistake)

```
WARNING: DATA RACE
Read at 0x00c4201a44f0 by goroutine 13:
  os/exec.(*Cmd).Wait()
      GOROOT/src/os/exec/exec.go:456 +0x8c
  github.com/bazelbuild/rules_webtesting/go/wsl/hub.(*Hub).quitSession()
      external/io_bazel_rules_webtesting/go/wsl/hub/hub.go:231 +0x148
  github.com/bazelbuild/rules_webtesting/go/wsl/hub.(*Hub).ServeHTTP()
      external/io_bazel_rules_webtesting/go/wsl/hub/hub.go:74 +0x736
  net/http.(*ServeMux).ServeHTTP()
      GOROOT/src/net/http/server.go:2337 +0x9f
  net/http.serverHandler.ServeHTTP()
      GOROOT/src/net/http/server.go:2694 +0xb9
  net/http.(*conn).serve()
      GOROOT/src/net/http/server.go:1830 +0x7dc
Previous write at 0x00c4201a44f0 by goroutine 45:
  os/exec.(*Cmd).Wait()
      GOROOT/src/os/exec/exec.go:459 +0xb1
  github.com/bazelbuild/rules_webtesting/go/wsl/driver.New.func1()
      external/io_bazel_rules_webtesting/go/wsl/driver/driver.go:100 +0x50
Goroutine 13 (running) created at:
  net/http.(*Server).Serve()
      GOROOT/src/net/http/server.go:2795 +0x364
  net/http.(*Server).ListenAndServe()
      GOROOT/src/net/http/server.go:2711 +0xc4
  github.com/bazelbuild/rules_webtesting/go/wsl.startServer.func1()
      external/io_bazel_rules_webtesting/go/wsl/wsl.go:52 +0xcb
Goroutine 45 (running) created at:
  github.com/bazelbuild/rules_webtesting/go/wsl/driver.New()
      external/io_bazel_rules_webtesting/go/wsl/driver/driver.go:99 +0x4fe
  github.com/bazelbuild/rules_webtesting/go/wsl/hub.(*Hub).newSessionJWPCaps()
      external/io_bazel_rules_webtesting/go/wsl/hub/hub.go:203 +0x18c
  github.com/bazelbuild/rules_webtesting/go/wsl/hub.(*Hub).newSession()
      external/io_bazel_rules_webtesting/go/wsl/hub/hub.go:123 +0x5b9
  github.com/bazelbuild/rules_webtesting/go/wsl/hub.(*Hub).ServeHTTP()
      external/io_bazel_rules_webtesting/go/wsl/hub/hub.go:58 +0xa23
  net/http.(*ServeMux).ServeHTTP()
      GOROOT/src/net/http/server.go:2337 +0x9f
  net/http.serverHandler.ServeHTTP()
      GOROOT/src/net/http/server.go:2694 +0xb9
  net/http.(*conn).serve()
      GOROOT/src/net/http/server.go:1830 +0x7dc
```

### PR DESCRIPTION
**Pull request by jmhodges**
Fixes #228 

I also have a fix_race_test branch that includes a test case that should exercise it, but I'm not sure what to use as the `"binary"` for it. If we solve that, I think I can make a test that will trip the race I'm fixing here.

### CODE REVIEW

**Comment by jmhodges** [comment]
Ugh, this seems to softlock when used in my repo. I'll try to take another crack at it.

**Comment by jmhodges** [comment]
There we go. Just pushed up a working version

**Comment by DrMarcII** [comment]
Thanks for the fix. As for the test, how about some standard command-line tool that doesn't immediatly exit; eg /bin/cat should work.

**Comment by jmhodges** [comment]
Unfortunately, that doesn't work, because cat, ls, etc all finish before the New function returns and the code we need to trigger is outside of it.

(Also, there seems to be some desire for Windows support and that would limit it?)

**Comment by DrMarcII** [comment]
Can you just use the chromedriver or geckodriver binary then?

**Comment by jmhodges** [comment]
Totally! I just didn't know how to refer to them inside the repo. I couldn't quite get the sense of everything.

**Pull request merged**
