### PR TITLE
Add go_repository rule for importing go packages.

### PR DESCRIPTION
**Pull request by DrMarcII**
- Remove redundancy from go import paths.

### CODE REVIEW

**Comment by jart** [comment]
This change is already in the other pull request for testing, correct? If so, I'm still planning on patching that internally. Just have a few other pressing concerns at the moment. I'll be able to take that on in the next few days, and I'm happy to do it as part of the other PR.

**Comment by DrMarcII** [comment]
Which other pull request are you talking about? If you mean the one for tensorflow, it is currently pinned to an earlier version of rules_webtesting, but this PR is just a cleanup thing.

No worries about reviewing this change. People on my team can take care of that (I probably should just go ahead and disable mention bot, as it hasn't been very useful).

**Comment by jart** [comment]
Oh whoops. I thought this was on TensorFlow for some reason.

**Comment by achew22** [comment]
What do you think about moving to the rules_go's [new_go_repository](https://github.com/bazelbuild/rules_go#new_go_repository)? It uses [Gazelle](https://github.com/bazelbuild/rules_go/tree/master/go/tools/gazelle) to automatically generate build files by parsing the Golang files and detecting their dependencies. If run inside your own repo it will even write your BUILD files for you so that you don't need to think about them any more.

**Comment by DrMarcII** [comment]
Hmm, I hadn't looked at new_go_repository before.

It looks like it has a couple of issues:
1. It uses an equivalent git_repository, which at least one of my target customers is not a fan of (@jart can add more context for why).
2. I want my imports of external libraries to not have to include :go_default_library (which is what the alias in my generated BUILD file is for). I have already filed an issue w.r.t. this at https://github.com/bazelbuild/rules_go/issues/265.

Additionally, I have played a little with Gazelle in my project and haven't yet figured out how to get it working correctly. It hasn't been a high priority for me, so I haven't dug too deep yet.

**Pull request merged**
