### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by dslomov**
Adding GitHub repo admin to global CODEOWNERS

### CODE REVIEW

**Comment by dslomov** [comment]
friendly ping @DrMarcII

**Comment by DrMarcII** [comment]
What is the purpose of the CODEOWNERS that is not already satisified by the fact that this is in the bazelbuild org and has a CONTRIBUTORS file?

**Comment by dslomov** [comment]
you will be assigned code reviews by default and your status as admin and a
responsible person for this repo will be visible to the community.
More info about codeowners here:
https://help.github.com/articles/about-code-owners/

**Comment by dslomov** [comment]
Friendly ping.

**Pull request merged**
